import api from './axios'

export const dashboard = () => api.get('/relatorios/dashboard')
export const dashboardGraficos = (params) => api.get('/relatorios/dashboard/graficos', { params })
export const dashboardGerencialTransferencias = (params) => api.get('/relatorios/dashboard-gerencial/transferencias', { params })
export const abastecimentos = (params) => api.get('/relatorios/abastecimentos', { params })
export const abastecimentosPdf = (params) => api.get('/relatorios/abastecimentos/pdf', { params, responseType: 'blob' })
export const viagens = (params) => api.get('/relatorios/viagens', { params })
export const viagensPdf = (params) => api.get('/relatorios/viagens/pdf', { params, responseType: 'blob' })
export const motoristas = () => api.get('/relatorios/motoristas')
export const motoristasPdf = () => api.get('/relatorios/motoristas/pdf', { responseType: 'blob' })
export const checkins = () => api.get('/relatorios/checkins')
export const manutencoes = (params) => api.get('/relatorios/manutencoes', { params })
export const manutencoesPdf = (params) => api.get('/relatorios/manutencoes/pdf', { params, responseType: 'blob' })
export const checklistVeiculo = (params) => api.get('/relatorios/checklist-veiculo', { params })
